---


- name: 'Executando o comando => rm /etc/apt/preferences.d/nosnap.pref'
  shell: 'rm /etc/apt/preferences.d/nosnap.pref'
  ignore_errors: yes
  become: true
  tags:
    - fix
    - snapd



- name: "Instalando o pacote {{ snapd_package }}"
  apt:
    name: "{{ snapd_package }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - snapd
