---

- name: "Instalando as Dependências do Snap"
  dnf:
    name: "{{ deps }}"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - deps
    - snapd


- name: "Instalando o pacote {{ snapd_package }}"
  dnf:
    name: "{{ snapd_package }}"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - snapd


- name: "Criar um link simbólico "
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  become: true
  tags:
    - fix
  