---


- name: Incluindo variaveis especificas do SO
  include_vars: "{{ item }}"
  with_first_found:
   - ../vars/{{ ansible_distribution | lower }}.yml
   - ../vars/{{ ansible_os_family | lower }}.yml
   - ../vars/os_defaults.yml
  tags: 
   - main



- name: Incluindo tarefas especificas para o SO
  include_tasks: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution | lower }}.yml"
   - "{{ ansible_os_family | lower }}.yml"
   - "os_defaults.yml"
  tags: 
   - main


- name: "FIX - Utilizando o comando source em /etc/profile"
  when: os_default is not defined
  shell: "source /etc/profile"
  args:
    executable: /bin/bash
  become: true
  tags:
    - snapd
    - fix


- name: "FIX - Iniciando o serviço snapd"
  when: os_default is not defined
  shell: "systemctl start snapd"
  args:
    executable: /bin/bash
  become: true
  tags:
    - snapd
    - fix


- name: "FIX - Habilitando o serviço snapd"
  when: os_default is not defined
  shell: "systemctl enable snapd"
  args:
    executable: /bin/bash
  become: true
  tags:
    - snapd
    - fix


- name: "FIX - Iniciando o serviço snapd.apparmor"
  when: os_default is not defined and ansible_distribution == "openSUSE Tumbleweed"
  shell: "systemctl start snapd.apparmor"
  args:
    executable: /bin/bash
  become: true
  tags:
    - snapd
    - fix


- name: "FIX - Habilitando o serviço snapd.apparmor"
  when: os_default is not defined and ansible_distribution == "openSUSE Tumbleweed"
  shell: "systemctl enable snapd.apparmor"
  args:
    executable: /bin/bash
  become: true
  tags:
    - snapd
    - fix